# fly.toml app configuration file generated for 9-job-centre on 2024-03-15T23:30:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '9-job-centre'
primary_region = 'lhr'

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]
[build.args]
BP_GO_TARGETS = "./9-job-centre/cmd/"
BP_GO_BUILD_FLAGS = "-modfile=./go.mod"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 8080


[services.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 1000


[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
