# fly.toml app configuration file generated for 4-unusual-database-program on 2023-12-28T14:01:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "4-unusual-database-program"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]
[build.args]
BP_GO_TARGETS = "./4-unusual-database-program/cmd/"
BP_GO_BUILD_FLAGS = "-modfile=./go.mod"

[env]
PORT = "5000"

[[services]]
protocol = "udp"
internal_port = 5000

[[services.ports]]
port = 5000

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
