# fly.toml file generated for 2-means-to-an-end on 2023-03-12T15:10:05-04:00

app = "2-means-to-an-end"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
  BP_GO_TARGETS = "./cmd/"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 8080

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
